### ISSUE TITLE
How to generate a package metadata hex?

### ISSUE THREAD

**Issue by adirutwn** [OmniBTC/Aptos-AMM-swap#4]
Hey,

I see that you put a raw hex here: https://github.com/OmniBTC/Aptos-AMM-swap/blob/main/tests/interface_tests.move#L122. Wondering how could one generate a package metadata hex?

I try:
```
hexdump -ve '1/1 "%02x"' ./build/lp/package-metadata.bcs
```
But it ends up different result than yours, while using the same command above with `.mv` ends up the same result.

**Comment by icodezjb** [comment]
@adirutwn 
```
let data = fs.readFileSync('package-metadata.bcs');
console.log(data.toString("hex"))

let data = fs.readFileSync('lp_coin.mv');
console.log(data.toString("hex"))
```
